### ISSUE TITLE
Error on SAMPLESHEET_CHECK

### ISSUE THREAD

**Issue by chstellar** [salzman-lab/nomad#45]
Hi, I was running NOMAD on two fastq.gz files to identify the variation between the two. I run:
`nextflow run salzmanlab/nomad -profile conda -r main -latest -resume --input sheet.csv --element_annotations_samplesheet /import/home/jyubq/PROJ_splash/splash/nomad_element_annotation_indices.tar.gz --run_annotations false`

and I got an error at SAMPLESHEET_CHECK:
`Sep-06 18:35:39.523 [Actor Thread 31] ERROR nextflow.extension.DataflowHelper - @unknown
java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:388)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:219)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:173)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:189)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.read1(BufferedReader.java:226)
	at java.base/java.io.BufferedReader.implRead(BufferedReader.java:315)
	at java.base/java.io.BufferedReader.read(BufferedReader.java:297)
	at java.base/java.io.Reader.read(Reader.java:265)
	at nextflow.splitter.AbstractTextSplitter.positionAfterBOM(AbstractTextSplitter.groovy:335)
	at nextflow.splitter.AbstractTextSplitter.normalizeSource(AbstractTextSplitter.groovy:114)
	at nextflow.splitter.AbstractTextSplitter.normalizeSource(AbstractTextSplitter.groovy)
	at nextflow.splitter.AbstractSplitter.apply(AbstractSplitter.groovy:153)
	at nextflow.extension.SplitOp$_applySplittingOperator_closure1.doCall(SplitOp.groovy:189)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.extension.DataflowHelper$_subscribeImpl_closure2.doCall(DataflowHelper.groovy:284)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
	at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
	at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
	at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
	at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
	at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Sep-06 18:35:39.529 [Actor Thread 31] DEBUG nextflow.Session - Session aborted -- Cause: Input length = 1
...
Sep-06 18:35:39.558 [Actor Thread 19] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=RUN_NOMAD:NOMAD:SAMPLESHEET_CHECK; work-dir=null
  error [java.lang.InterruptedException]: java.lang.InterruptedException`

My sample file has three rows and one column:
fastq_file
/import/home/jyubq/PROJ_splash/mussel_raw/mussel_bacterio.fastq.gz
/import/home/jyubq/PROJ_splash/mussel_raw/mussel_vepc.fastq.gz

I was running this on hpc with Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-79-generic x86_64). Could you please help with this? Many thanks.

**Comment by TavorB** [comment]
Thanks for reaching out. I believe that the issue with your samplesheet is that it has a header (the first row of "fastq_file" should be deleted), as in the example samplesheet: https://github.com/salzman-lab/nomad/blob/main/test_samplesheet.csv.

Also, since initially publicizing this repository, we have worked with collaborators to produce an improved codebase (both statistically and computationally) which I would highly recommend using. The new repo can be found here: https://github.com/refresh-bio/SPLASH. Please let us know if you have any additional questions!

**Comment by chstellar** [comment]
Thanks for the quick response! I removed the header but what made things worked was that I input the sample sheet into --element_annotation_flies but not --input.
